"use strict";
const $=s=>document.querySelector(s);
const form=$("#messageForm"),nickname=$("#nickname"),mood=$("#mood"),message=$("#message"),remember=$("#rememberName"),list=$("#messageList"),empty=$("#emptyState"),emptyTitle=$("#emptyTitle"),emptyText=$("#emptyText"),emptyAction=$("#emptyAction"),search=$("#searchInput"),searchClear=$("#searchClear"),sort=$("#sortSelect"),charCount=$("#charCount"),charCounter=$("#charCounter"),messageCount=$("#messageCount"),likeCount=$("#likeCount"),heroStats=$("#heroStats"),toast=$("#toast"),themeToggle=$("#themeToggle"),connectionStatus=$("#connectionStatus"),submitButton=$("#submitButton"),refreshButton=$("#refreshButton"),deleteModal=$("#deleteModal"),cancelDelete=$("#cancelDelete"),confirmDelete=$("#confirmDelete"),moodCurrent=$("#moodCurrent"),pagination=$("#pagination"),paginationPages=$("#paginationPages"),prevPage=$("#prevPage"),nextPage=$("#nextPage");
const config=window.AUCEI_GUESTBOOK_CONFIG||{},API_BASE=String(config.apiBaseUrl||"").replace(/\/$/,""),REQUEST_TIMEOUT=Number(config.requestTimeout)||10000;
const NAME_KEY="aucei-guestbook-name",VISITOR_KEY="aucei-guestbook-visitor",DELETE_TOKENS_KEY="aucei-guestbook-delete-tokens";
const PAGE_SIZE=5;
let messages=[],toastTimer=0,pendingDelete=null,lastDeleteTrigger=null,currentPage=1,listTransitionTimer=0,searchTimer=0,isFirstLoad=true;
const expandedReplies=new Set(),visibleReplyThreads=new Set(),replyTargets=new Map();
function storageGet(key,fallback=""){try{return localStorage.getItem(key)||fallback}catch{return fallback}}
function storageSet(key,value){try{localStorage.setItem(key,value)}catch{}}
function visitorId(){let id=storageGet(VISITOR_KEY);if(!id){id=crypto.randomUUID?.()||`v-${Date.now()}-${Math.random().toString(36).slice(2)}`;storageSet(VISITOR_KEY,id)}return id}
function deleteTokens(){try{return JSON.parse(storageGet(DELETE_TOKENS_KEY,"{}"))||{}}catch{return {}}}
function saveDeleteToken(id,token){const tokens=deleteTokens();tokens[id]=token;storageSet(DELETE_TOKENS_KEY,JSON.stringify(tokens))}
function removeDeleteToken(id){const tokens=deleteTokens();delete tokens[id];storageSet(DELETE_TOKENS_KEY,JSON.stringify(tokens))}
function esc(value){const node=document.createElement("div");node.textContent=String(value??"");return node.innerHTML}
function avatarColor(name){let n=0;for(const c of name)n=(n*31+c.charCodeAt(0))>>>0;const sets=[["#8b6cff","#22d3ee"],["#ff758d","#9b6bff"],["#18b981","#22b8cf"],["#f59f00","#ff6b6b"],["#4c6ef5","#845ef7"]],pair=sets[n%sets.length];return`linear-gradient(135deg,${pair[0]},${pair[1]})`}
function timeText(value){const t=new Date(value).getTime(),diff=Date.now()-t,min=60000,hour=3600000,day=86400000;if(diff<min)return"刚刚";if(diff<hour)return`${Math.floor(diff/min)} 分钟前`;if(diff<day)return`${Math.floor(diff/hour)} 小时前`;if(diff<day*7)return`${Math.floor(diff/day)} 天前`;return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(t))}
function showToast(text){toast.textContent=text;toast.classList.remove("is-open");void toast.offsetWidth;toast.classList.add("is-open");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("is-open"),1800)}
function setStatus(state){const states={connecting:["正在连接","is-connecting"],online:["云端正常","is-online"],error:["网络异常","is-error"]},[text,mode]=states[state]||states.connecting;connectionStatus.className=`connection-status ${mode}`;connectionStatus.querySelector("span").textContent=text;connectionStatus.setAttribute("aria-label",state==="error"?"网络异常，点击重新连接":text)}
async function getIpipLocation(){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);
  try{
    const response=await fetch("https://myip.ipip.net/",{method:"GET",mode:"cors",cache:"no-store",signal:controller.signal,headers:{Accept:"text/plain"}});
    if(!response.ok)return null;
    const text=(await response.text()).trim();
    const ip=(text.match(/(?:当前\s*IP|IP)[:：]\s*([0-9a-fA-F:.]+)/)||[])[1]||"";
    const source=(text.match(/来自于[:：]\s*(.+)$/)||[])[1]||"";
    const parts=source.split(/\s+/).filter(Boolean);
    if(!ip||!parts.length)return null;
    return {ip,country:parts[0]||"",province:parts[1]||"",city:parts[2]||"",isp:parts.slice(3).join(" "),raw:text.slice(0,160)};
  }catch{return null}finally{clearTimeout(timer)}
}
function getBrowserLocation(){
  return new Promise(resolve=>{
    if(!navigator.geolocation||!window.isSecureContext){resolve(null);return}
    navigator.geolocation.getCurrentPosition(
      position=>resolve({
        latitude:Number(position.coords.latitude.toFixed(6)),
        longitude:Number(position.coords.longitude.toFixed(6)),
        accuracy:Math.round(Number(position.coords.accuracy)||0)
      }),
      ()=>resolve(null),
      {enableHighAccuracy:true,timeout:10000,maximumAge:60000}
    )
  })
}
async function getClientInfo(){const ua=navigator.userAgent||"",d=navigator.userAgentData;let h={};try{if(d?.getHighEntropyValues)h=await d.getHighEntropyValues(["model"])}catch{}const v=r=>ua.match(r)?.[1]||"",android=/Android/i.test(ua),ios=/iPhone|iPad|iPod/i.test(ua);let deviceModel=String(h.model||"").trim();if(!deviceModel&&android)deviceModel=v(/Android[^;]*;\s*([^;)]+?)\s+Build\//i).trim();if(!deviceModel&&ios)deviceModel=/iPad/i.test(ua)?"iPad":"iPhone";const deviceType=/iPad|Tablet/i.test(ua)||(android&&!/Mobile/i.test(ua))?"平板":d?.mobile||/Mobile|Android|iPhone|iPod/i.test(ua)?"手机":"电脑",osName=android?`Android ${v(/Android\s+([\d.]+)/i)}`:ios?`iOS ${v(/(?:CPU(?: iPhone)? OS|iPhone OS)\s+([\d_]+)/i).replaceAll("_",".")}`:/Windows/i.test(ua)?"Windows":/Mac/i.test(ua)?"macOS":/Linux/i.test(ua)?"Linux":"其他系统";const ver=r=>v(r);let browserName=/wxwork/i.test(ua)?`企业微信 ${ver(/MicroMessenger\/([\d.]+)/i)}`:/MicroMessenger/i.test(ua)?`微信内置浏览器 ${ver(/MicroMessenger\/([\d.]+)/i)}`:/AlipayClient/i.test(ua)?`支付宝内置浏览器 ${ver(/AlipayClient\/([\d.]+)/i)}`:/Aweme|BytedanceWebview/i.test(ua)?"抖音内置浏览器":/QQ\//i.test(ua)&&!/QQBrowser/i.test(ua)?`QQ 内置浏览器 ${ver(/QQ\/([\d.]+)/i)}`:/Edg/i.test(ua)?"Edge":/SamsungBrowser/i.test(ua)?"Samsung Internet":/HuaweiBrowser/i.test(ua)?"华为浏览器":/MiuiBrowser/i.test(ua)?"小米浏览器":/UCBrowser|UCWEB/i.test(ua)?"UC 浏览器":/QQBrowser/i.test(ua)?"QQ 浏览器":/Firefox|FxiOS/i.test(ua)?"Firefox":/Chrome|CriOS/i.test(ua)?"Chrome":/Safari/i.test(ua)?"Safari":"其他浏览器";const browserEngine=/AppleWebKit/i.test(ua)?(ios||/Mac/i.test(ua)?"WebKit":/XWEB|TBS|MQQBrowser/i.test(ua)?"腾讯 X5 / Chromium":"Chromium"):/Gecko\//i.test(ua)?"Gecko":"未识别";return{deviceType,deviceModel:deviceModel||"未提供",osName:osName.trim(),browserName:browserName.trim(),browserEngine}}
function friendlyError(error){if(!navigator.onLine)return"网络已断开，请检查网络后重试";if(error?.name==="AbortError")return"连接超时，请稍后重试";const text=String(error?.message||"");if(/failed to fetch|networkerror|load failed|fetch failed/i.test(text))return"无法连接云端，请检查网络后重试";return text||"网络异常，请稍后重试"}
async function api(path,options={}){if(!API_BASE||API_BASE.includes("YOUR-WORKER-NAME"))throw new Error("请先配置后端 API 地址");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT);try{const response=await fetch(`${API_BASE}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})},signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`请求失败 (${response.status})`);return data}finally{clearTimeout(timer)}}
function filteredMessages(){const q=search.value.trim().toLowerCase();return messages.filter(x=>`${x.name} ${x.content} ${(x.replies||[]).map(r=>`${r.name} ${r.replyToName||""} ${r.content}`).join(" ")}`.toLowerCase().includes(q)).sort((a,b)=>{if(Boolean(a.isPinned)!==Boolean(b.isPinned))return a.isPinned?-1:1;if(a.isPinned&&b.isPinned)return new Date(b.pinnedAt||b.createdAt)-new Date(a.pinnedAt||a.createdAt);return sort.value==="oldest"?new Date(a.createdAt)-new Date(b.createdAt):sort.value==="likes"?b.likes-a.likes:new Date(b.createdAt)-new Date(a.createdAt)})}
function updateEmptyState(data){const searching=Boolean(search.value.trim());empty.hidden=data.length>0;if(data.length)return;if(searching&&messages.length){emptyTitle.textContent="没有找到相关留言";emptyText.textContent="换一个关键词试试看。";emptyAction.hidden=false}else{emptyTitle.textContent="这里还很安静";emptyText.textContent="成为第一个留下脚印的人吧。";emptyAction.hidden=true}}
function renderPagination(totalItems,totalPages){pagination.hidden=totalItems<=PAGE_SIZE;if(pagination.hidden){paginationPages.innerHTML="";return}prevPage.disabled=currentPage===1;nextPage.disabled=currentPage===totalPages;const pages=[];for(let page=1;page<=totalPages;page++){if(totalPages<=7||page===1||page===totalPages||Math.abs(page-currentPage)<=1){pages.push(`<button class="pagination__number${page===currentPage?" is-current":""}" type="button" data-page="${page}" aria-label="第 ${page} 页" aria-current="${page===currentPage?"page":"false"}">${page}</button>`)}else if(pages[pages.length-1]!=="…"){pages.push("…")}}paginationPages.innerHTML=pages.map(item=>item==="…"?'<span class="pagination__ellipsis" aria-hidden="true">…</span>':item).join("")}
function goToPage(page){const totalPages=Math.max(1,Math.ceil(filteredMessages().length/PAGE_SIZE)),next=Math.min(Math.max(1,page),totalPages);if(next===currentPage)return;currentPage=next;render(false,true);document.querySelector(".messages-section")?.scrollIntoView({behavior:"smooth",block:"start"})}
function skeletonCards(count=5){return Array.from({length:count},(_,index)=>`<article class="message-card message-skeleton" style="--skeleton-index:${index}"><div class="skeleton-top"><span class="skeleton-block skeleton-avatar"></span><div><span class="skeleton-block skeleton-name"></span><span class="skeleton-block skeleton-time"></span></div></div><span class="skeleton-block skeleton-line skeleton-line--wide"></span><span class="skeleton-block skeleton-line skeleton-line--short"></span><div class="skeleton-bottom"><span class="skeleton-block skeleton-action"></span><span class="skeleton-block skeleton-id"></span></div></article>`).join("")}
function showListSkeleton(){list.className="message-list is-loading";list.setAttribute("aria-busy","true");list.innerHTML=skeletonCards(PAGE_SIZE);empty.hidden=true;pagination.hidden=true}
function render(animate=true,transition=false){if(!transition){renderNow(animate);return}clearTimeout(listTransitionTimer);list.classList.remove("is-entering");list.classList.add("is-leaving");list.setAttribute("aria-busy","true");listTransitionTimer=window.setTimeout(()=>{renderNow(false);list.classList.remove("is-leaving");list.classList.add("is-entering");list.setAttribute("aria-busy","false");requestAnimationFrame(()=>requestAnimationFrame(()=>list.classList.remove("is-entering")))},170)}
function replyMarkup(messageItem,tokens){
  const replies=(Array.isArray(messageItem.replies)?[...messageItem.replies]:[]).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)),expanded=expandedReplies.has(messageItem.id),visible=expanded?replies:replies.slice(0,2),hiddenCount=Math.max(0,replies.length-visible.length),target=replyTargets.get(messageItem.id);
  const formMarkup=`<form class="reply-form" data-reply-form ${target?"":"hidden"}><div class="reply-form__heading"><span>${target?.replyId?`回复 @${esc(target.name)}`:`回复 @${esc(messageItem.name)}`}</span><button type="button" data-action="reply-cancel" aria-label="取消回复">×</button></div><div class="reply-form__row"><span class="reply-avatar reply-avatar--form" style="--avatar:${avatarColor(nickname.value||storageGet(NAME_KEY)||"访客")}">${esc([...(nickname.value||storageGet(NAME_KEY)||"访")][0])}</span><div class="reply-form__inputs"><input name="replyName" maxlength="16" placeholder="你的昵称" value="${esc(nickname.value||storageGet(NAME_KEY))}" required><textarea name="replyContent" maxlength="180" rows="3" placeholder="友善回复一下……" required></textarea></div></div><div class="reply-form__footer"><span class="reply-counter">0/180</span><button class="reply-submit" type="submit">发布回复</button></div></form>`;
  const listMarkup=replies.length?`<div class="reply-list">${visible.map(reply=>`<article class="reply-item" data-reply-id="${esc(reply.id)}"><span class="reply-avatar" style="--avatar:${avatarColor(reply.name)}">${esc([...reply.name][0]||"访")}</span><div class="reply-main"><div class="reply-meta"><strong>${esc(reply.name)}</strong>${reply.isAdmin?'<span class="admin-reply-badge">站长</span>':""}${reply.owned?'<span class="reply-owner-badge">我</span>':""}</div><p>${reply.replyToName?`<span class="reply-to">回复 <b>@${esc(reply.replyToName)}</b>：</span>`:""}${esc(reply.content)}</p><div class="reply-footer"><time>${esc(timeText(reply.createdAt))}</time>${reply.region?`<span class="reply-region">· ${esc(reply.region)}</span>`:""}<button class="reply-inline" type="button" data-action="reply-to">回复</button>${(reply.owned||tokens[reply.id])?'<button class="reply-delete" type="button" data-action="reply-delete" aria-label="删除回复" title="删除回复"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7h16"></path><path d="M9 7V4h6v3"></path><path d="m6 7 1 13h10l1-13"></path><path d="M10 11v5M14 11v5"></path></svg></button>':""}</div></div></article>`).join("")}${hiddenCount?`<button class="reply-expand" type="button" data-action="replies-toggle"><span class="reply-expand__line"></span>展开 ${hiddenCount} 条回复<span class="reply-expand__chevron" aria-hidden="true"></span></button>`:""}${expanded&&replies.length>2?'<button class="reply-expand" type="button" data-action="replies-toggle"><span class="reply-expand__line"></span>收起回复<span class="reply-expand__chevron is-up" aria-hidden="true"></span></button>':""}</div>`:"";
  return `<div class="reply-section">${listMarkup}${formMarkup}</div>`
}
function renderNow(animate=true){const data=filteredMessages(),tokens=deleteTokens(),totalPages=Math.max(1,Math.ceil(data.length/PAGE_SIZE));currentPage=Math.min(Math.max(1,currentPage),totalPages);const start=(currentPage-1)*PAGE_SIZE,pageData=data.slice(start,start+PAGE_SIZE);list.innerHTML=pageData.map(x=>`<article class="message-card${x.isPinned?" is-pinned":""}${x.isFeatured?" is-featured":""}${animate?"":" no-enter"}" data-id="${esc(x.id)}"><div class="message-card__top"><div class="author"><span class="avatar" style="--avatar:${avatarColor(x.name)}">${esc([...x.name][0]||"访")}</span><div><div class="author__name"><strong>${esc(x.name)}</strong>${x.isPinned?'<span class="message-badge pinned">置顶</span>':""}${x.isFeatured?'<span class="message-badge featured">精选</span>':""}${x.owned?'<span class="owner-badge">我的留言</span>':""}</div><small class="message-meta-time">${esc(timeText(x.createdAt))}${x.region?`<span class="message-region"> · ${esc(x.region)}</span>`:""}</small></div></div><span class="mood" aria-label="心情">${esc(x.mood)}</span></div><p class="message-card__body">${esc(x.content)}</p><div class="message-card__bottom"><div class="message-actions"><button class="like-button ${x.liked?"is-liked":""}" type="button" data-action="like" aria-label="${x.liked?"取消点赞":"点赞"}"><svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"></path></svg><span>${x.likes}</span></button><button class="reply-button" type="button" data-action="reply-toggle" aria-label="查看或发表回复"><svg viewBox="0 0 24 24"><path d="M9 17H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-5l-5 4v-4Z"></path></svg><span>${(x.replies||[]).length}</span></button></div>${(x.owned||tokens[x.id])?'<button class="delete-button" type="button" data-action="delete" aria-label="删除留言" title="删除留言"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7h16"></path><path d="M9 7V4h6v3"></path><path d="m6 7 1 13h10l1-13"></path><path d="M10 11v5M14 11v5"></path></svg></button>':`<span class="message-id"><span class="message-id__prefix">NO.</span><span class="message-id__number">${esc(String(x.displayId||String(x.id).slice(-3)).replace(/^0+/,"")||"0")}</span></span>`}</div>${replyMarkup(x,tokens)}</article>`).join("");updateEmptyState(data);renderPagination(data.length,totalPages);list.classList.remove("is-loading");list.setAttribute("aria-busy","false");updateStats(messages.length,messages.reduce((n,x)=>n+x.likes,0))}
function animateNumber(element,to,duration=520){const from=Number(element.textContent)||0;if(from===to){element.textContent=String(to);return}const start=performance.now(),step=now=>{const progress=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-progress,3);element.textContent=String(Math.round(from+(to-from)*eased));if(progress<1)requestAnimationFrame(step)};requestAnimationFrame(step)}
function updateStats(messageTotal,likeTotal,finishLoading=true){if(finishLoading&&heroStats.classList.contains("is-loading")){heroStats.classList.remove("is-loading");heroStats.classList.add("is-revealing");heroStats.setAttribute("aria-busy","false");window.setTimeout(()=>heroStats.classList.remove("is-revealing"),620)}animateNumber(messageCount,messageTotal);animateNumber(likeCount,likeTotal)}
async function loadMessages(animate=true){setStatus("connecting");refreshButton.disabled=true;refreshButton.classList.add("is-refreshing");refreshButton.setAttribute("aria-label","正在刷新留言");if(isFirstLoad)showListSkeleton();try{const data=await api(`/messages?visitorId=${encodeURIComponent(visitorId())}`);messages=Array.isArray(data.messages)?data.messages:[];if(isFirstLoad){window.setTimeout(()=>{renderNow(false);list.classList.add("is-initial-reveal");requestAnimationFrame(()=>requestAnimationFrame(()=>list.classList.remove("is-initial-reveal")))},180)}else render(animate,true);isFirstLoad=false;setStatus("online")}catch(error){isFirstLoad=false;renderNow(false);setStatus("error");showToast(friendlyError(error))}finally{refreshButton.disabled=false;refreshButton.classList.remove("is-refreshing");refreshButton.setAttribute("aria-label","刷新留言")}}
function setSubmitting(active){submitButton.disabled=active;submitButton.classList.toggle("is-loading",active);submitButton.querySelector(".submit-button__label").textContent=active?"正在发布…":"发布留言"}
form.addEventListener("submit",async e=>{e.preventDefault();const name=nickname.value.trim(),content=message.value.trim();if(!name){nickname.focus();showToast("请先填写昵称");return}if(!content){message.focus();showToast("留言内容不能为空");return}setSubmitting(true);try{const [location,clientInfo,ipipLocation]=await Promise.all([getBrowserLocation(),getClientInfo(),getIpipLocation()]);const data=await api("/messages",{method:"POST",body:JSON.stringify({name,mood:mood.value,content,visitorId:visitorId(),location,clientInfo,ipipLocation})});if(data.deleteToken)saveDeleteToken(data.message.id,data.deleteToken);if(remember.checked)storageSet(NAME_KEY,name);else try{localStorage.removeItem(NAME_KEY)}catch{}message.value="";updateCharacterCount();search.value="";searchClear.hidden=true;sort.value="newest";currentPage=1;messages.unshift(data.message);render(true);showToast("留言发布成功")}catch(error){showToast(friendlyError(error))}finally{setSubmitting(false)}})
function updateCharacterCount(){const length=message.value.length;charCount.textContent=length;charCounter.classList.toggle("is-near",length>=240&&length<270);charCounter.classList.toggle("is-limit",length>=270)}
message.addEventListener("input",updateCharacterCount);
document.querySelectorAll(".mood-option").forEach(button=>button.addEventListener("click",()=>{mood.value=button.dataset.mood;moodCurrent.textContent=button.dataset.label;document.querySelectorAll(".mood-option").forEach(item=>{const selected=item===button;item.classList.toggle("is-selected",selected);item.setAttribute("aria-checked",String(selected))})}));
function openDeleteModal(item,trigger,type="message",parent=null){pendingDelete={item,type,parent};deleteModal.querySelector("h2").textContent=type==="reply"?"删除这条回复？":"删除这条留言？";deleteModal.querySelector("p").textContent=type==="reply"?"回复删除后无法恢复，请确认是否继续。":"删除后无法恢复，请确认是否继续。";lastDeleteTrigger=trigger;deleteModal.hidden=false;document.body.classList.add("modal-open");requestAnimationFrame(()=>{deleteModal.classList.add("is-open");cancelDelete.focus()})}
function closeDeleteModal(){deleteModal.classList.remove("is-open");document.body.classList.remove("modal-open");setTimeout(()=>deleteModal.hidden=true,180);pendingDelete=null;lastDeleteTrigger?.focus();lastDeleteTrigger=null}
async function deletePending(){if(!pendingDelete)return;const {item,type,parent}=pendingDelete,token=deleteTokens()[item.id];confirmDelete.disabled=true;confirmDelete.textContent="正在删除…";try{if(type==="reply"){await api(`/replies/${encodeURIComponent(item.id)}`,{method:"DELETE",headers:{"X-Delete-Token":token||"","X-Visitor-Id":visitorId()}});parent.replies=(parent.replies||[]).filter(r=>r.id!==item.id);removeDeleteToken(item.id);closeDeleteModal();renderNow(false);showToast("回复已删除")}else{const card=list.querySelector(`[data-id="${CSS.escape(String(item.id))}"]`);await api(`/messages/${encodeURIComponent(item.id)}`,{method:"DELETE",headers:{"X-Delete-Token":token||"","X-Visitor-Id":visitorId()}});card?.classList.add("is-removing");messages=messages.filter(x=>x.id!==item.id);currentPage=Math.min(currentPage,Math.max(1,Math.ceil(filteredMessages().length/PAGE_SIZE)));removeDeleteToken(item.id);closeDeleteModal();setTimeout(()=>render(false),230);showToast("留言已删除")}}catch(error){showToast(friendlyError(error))}finally{confirmDelete.disabled=false;confirmDelete.textContent="确认删除"}}
list.addEventListener("click",async e=>{const btn=e.target.closest("button[data-action]"),card=e.target.closest(".message-card");if(!btn||!card)return;const item=messages.find(x=>String(x.id)===card.dataset.id);if(!item)return;const action=btn.dataset.action;if(action==="delete"){openDeleteModal(item,btn);return}if(action==="reply-toggle"){
  if(replyTargets.has(item.id)){
    replyTargets.delete(item.id);
    renderNow(false);
  }else{
    replyTargets.set(item.id,{replyId:null,name:item.name});
    renderNow(false);
    list.querySelector(`[data-id="${CSS.escape(String(item.id))}"] textarea[name="replyContent"]`)?.focus();
  }
  return
}if(action==="reply-to"){const replyId=btn.closest(".reply-item")?.dataset.replyId,reply=(item.replies||[]).find(r=>String(r.id)===replyId);if(reply){visibleReplyThreads.add(item.id);replyTargets.set(item.id,{replyId:reply.id,name:reply.name});renderNow(false);list.querySelector(`[data-id="${CSS.escape(String(item.id))}"] textarea[name="replyContent"]`)?.focus()}return}if(action==="reply-cancel"){replyTargets.delete(item.id);renderNow(false);return}if(action==="replies-toggle"){expandedReplies.has(item.id)?expandedReplies.delete(item.id):expandedReplies.add(item.id);renderNow(false);return}if(action==="reply-delete"){const replyId=btn.closest(".reply-item")?.dataset.replyId,reply=(item.replies||[]).find(r=>String(r.id)===replyId);if(reply)openDeleteModal(reply,btn,"reply",item);return}if(action!=="like")return;btn.disabled=true;try{const data=await api(`/messages/${encodeURIComponent(item.id)}/like`,{method:"POST",body:JSON.stringify({visitorId:visitorId()})});item.liked=data.liked;item.likes=data.likes;btn.classList.toggle("is-liked",item.liked);btn.setAttribute("aria-label",item.liked?"取消点赞":"点赞");btn.querySelector("span").textContent=String(item.likes);const heart=btn.querySelector("svg");heart.classList.remove("is-popping");void heart.offsetWidth;heart.classList.add("is-popping");updateStats(messages.length,messages.reduce((n,x)=>n+x.likes,0),false)}catch(error){showToast(friendlyError(error))}finally{btn.disabled=false}})
list.addEventListener("input",e=>{if(e.target.name==="replyContent"){const counter=e.target.closest("form")?.querySelector(".reply-counter");if(counter)counter.textContent=`${e.target.value.length}/180`}})
list.addEventListener("submit",async e=>{const f=e.target.closest("form[data-reply-form]");if(!f)return;e.preventDefault();const card=f.closest(".message-card"),item=messages.find(x=>String(x.id)===card?.dataset.id),target=replyTargets.get(item.id)||{replyId:null,name:item.name},name=f.elements.replyName.value.trim(),content=f.elements.replyContent.value.trim(),button=f.querySelector(".reply-submit");if(!name){f.elements.replyName.focus();showToast("请填写回复昵称");return}if(!content){f.elements.replyContent.focus();showToast("回复内容不能为空");return}button.disabled=true;button.textContent="正在发布…";try{const [location,clientInfo,ipipLocation]=await Promise.all([getBrowserLocation(),getClientInfo(),getIpipLocation()]);const data=await api(`/messages/${encodeURIComponent(item.id)}/replies`,{method:"POST",body:JSON.stringify({name,content,parentReplyId:target.replyId,visitorId:visitorId(),location,clientInfo,ipipLocation})});if(data.deleteToken)saveDeleteToken(data.reply.id,data.deleteToken);item.replies??=[];item.replies.push(data.reply);visibleReplyThreads.add(item.id);expandedReplies.add(item.id);replyTargets.delete(item.id);if(remember.checked)storageSet(NAME_KEY,name);renderNow(false);showToast(target.replyId?`已回复 @${target.name}`:"回复发布成功")}catch(error){showToast(friendlyError(error))}finally{button.disabled=false;button.textContent="发布回复"}})
search.addEventListener("input",()=>{searchClear.hidden=!search.value;currentPage=1;clearTimeout(searchTimer);searchTimer=window.setTimeout(()=>render(false,true),180)});searchClear.addEventListener("click",()=>{search.value="";searchClear.hidden=true;currentPage=1;search.focus();render(false,true)});emptyAction.addEventListener("click",()=>searchClear.click());sort.addEventListener("change",()=>{currentPage=1;render(false,true)});paginationPages.addEventListener("click",e=>{const button=e.target.closest("button[data-page]");if(button)goToPage(Number(button.dataset.page))});prevPage.addEventListener("click",()=>goToPage(currentPage-1));nextPage.addEventListener("click",()=>goToPage(currentPage+1));
refreshButton.addEventListener("click",async()=>{await loadMessages(false);if(connectionStatus.classList.contains("is-online"))showToast("留言已刷新")});
connectionStatus.addEventListener("click",()=>{if(connectionStatus.classList.contains("is-error"))loadMessages(false)});cancelDelete.addEventListener("click",closeDeleteModal);confirmDelete.addEventListener("click",deletePending);deleteModal.addEventListener("click",e=>{if(e.target.hasAttribute("data-close-modal"))closeDeleteModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!deleteModal.hidden)closeDeleteModal()});
function initTheme(){
  const root=document.documentElement;
  const saved=storageGet("card-theme");
  const initial=saved||(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark");
  commitTheme(initial);
  themeToggle.addEventListener("click",()=>{
    if(root.classList.contains("theme-changing"))return;
    const next=root.classList.contains("light")?"dark":"light";
    root.classList.add("theme-changing");
    themeToggle.disabled=true;
    const finish=()=>window.setTimeout(()=>{
      root.classList.remove("theme-changing");
      themeToggle.disabled=false;
    },80);
    if(document.startViewTransition){
      const transition=document.startViewTransition(()=>commitTheme(next));
      transition.finished.finally(finish);
    }else{
      void root.offsetWidth;
      requestAnimationFrame(()=>requestAnimationFrame(()=>{
        commitTheme(next);
        window.setTimeout(finish,620);
      }));
    }
    storageSet("card-theme",next);
  });
  function commitTheme(theme){
    const light=theme==="light";
    root.classList.toggle("light",light);
    themeToggle.setAttribute("aria-pressed",String(light));
    themeToggle.setAttribute("aria-label",light?"切换到深色主题":"切换到浅色主题");
  }
}
nickname.value=storageGet(NAME_KEY);$("#currentYear").textContent=new Date().getFullYear();initTheme();updateCharacterCount();loadMessages();
