"use strict";
const $=s=>document.querySelector(s);
const form=$("#messageForm"),nickname=$("#nickname"),mood=$("#mood"),message=$("#message"),remember=$("#rememberName"),list=$("#messageList"),empty=$("#emptyState"),search=$("#searchInput"),sort=$("#sortSelect"),charCount=$("#charCount"),messageCount=$("#messageCount"),likeCount=$("#likeCount"),toast=$("#toast"),themeToggle=$("#themeToggle"),connectionStatus=$("#connectionStatus");
const config=window.AUCEI_GUESTBOOK_CONFIG||{};
const API_BASE=String(config.apiBaseUrl||"").replace(/\/$/,"");
const REQUEST_TIMEOUT=Number(config.requestTimeout)||10000;
const NAME_KEY="aucei-guestbook-name",VISITOR_KEY="aucei-guestbook-visitor",DELETE_TOKENS_KEY="aucei-guestbook-delete-tokens";
let messages=[],toastTimer=0,loadTimer=0;
function storageGet(key,fallback=""){try{return localStorage.getItem(key)||fallback}catch{return fallback}}
function storageSet(key,value){try{localStorage.setItem(key,value)}catch{}}
function visitorId(){let id=storageGet(VISITOR_KEY);if(!id){id=crypto.randomUUID?.()||`v-${Date.now()}-${Math.random().toString(36).slice(2)}`;storageSet(VISITOR_KEY,id)}return id}
function deleteTokens(){try{return JSON.parse(storageGet(DELETE_TOKENS_KEY,"{}"))||{}}catch{return {}}}
function saveDeleteToken(id,token){const tokens=deleteTokens();tokens[id]=token;storageSet(DELETE_TOKENS_KEY,JSON.stringify(tokens))}
function esc(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
function avatarColor(name){let n=0;for(const c of name)n=(n*31+c.charCodeAt(0))>>>0;const sets=[["#8b6cff","#22d3ee"],["#ff758d","#9b6bff"],["#18b981","#22b8cf"],["#f59f00","#ff6b6b"],["#4c6ef5","#845ef7"]],p=sets[n%sets.length];return`linear-gradient(135deg,${p[0]},${p[1]})`}
function timeText(value){const t=new Date(value).getTime(),diff=Date.now()-t,min=60000,hour=3600000,day=86400000;if(diff<min)return"刚刚";if(diff<hour)return`${Math.floor(diff/min)} 分钟前`;if(diff<day)return`${Math.floor(diff/hour)} 小时前`;if(diff<day*7)return`${Math.floor(diff/day)} 天前`;return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(t))}
function showToast(text){toast.textContent=text;toast.classList.remove("is-open");void toast.offsetWidth;toast.classList.add("is-open");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("is-open"),1800)}
function setStatus(text,error=false){if(!connectionStatus)return;connectionStatus.textContent=text;connectionStatus.classList.toggle("is-error",error)}
async function api(path,options={}){if(!API_BASE||API_BASE.includes("YOUR-WORKER-NAME"))throw new Error("请先配置后端 API 地址");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT);try{const response=await fetch(`${API_BASE}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})},signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`请求失败 (${response.status})`);return data}finally{clearTimeout(timer)}}
function filteredMessages(){const q=search.value.trim().toLowerCase();return messages.filter(x=>`${x.name} ${x.content}`.toLowerCase().includes(q)).sort((a,b)=>sort.value==="oldest"?new Date(a.createdAt)-new Date(b.createdAt):sort.value==="likes"?b.likes-a.likes:new Date(b.createdAt)-new Date(a.createdAt))}
function render(animate=true){const data=filteredMessages(),tokens=deleteTokens();list.innerHTML=data.map(x=>`<article class="message-card${animate?"":" no-enter"}" data-id="${esc(x.id)}"><div class="message-card__top"><div class="author"><span class="avatar" style="--avatar:${avatarColor(x.name)}">${esc([...x.name][0]||"访")}</span><div><strong>${esc(x.name)}</strong><small>${esc(timeText(x.createdAt))}</small></div></div><span class="mood" aria-label="心情">${esc(x.mood)}</span></div><p class="message-card__body">${esc(x.content)}</p><div class="message-card__bottom"><button class="like-button ${x.liked?"is-liked":""}" type="button" data-action="like" aria-label="${x.liked?"取消点赞":"点赞"}"><svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"></path></svg><span>${x.likes}</span></button>${(x.owned||tokens[x.id])?'<button class="delete-button" type="button" data-action="delete">删除</button>':`<span class="message-id">#${esc(x.displayId||String(x.id).slice(-3))}</span>`}</div></article>`).join("");empty.hidden=data.length>0;messageCount.textContent=messages.length;likeCount.textContent=messages.reduce((n,x)=>n+x.likes,0)}
async function loadMessages(animate=true){setStatus("正在连接云端");try{const data=await api(`/messages?visitorId=${encodeURIComponent(visitorId())}`);messages=Array.isArray(data.messages)?data.messages:[];render(animate);setStatus("云端已连接")}catch(error){messages=[];render(false);setStatus("云端连接失败",true);showToast(error.name==="AbortError"?"后端连接超时":error.message)}}
form.addEventListener("submit",async e=>{e.preventDefault();const name=nickname.value.trim(),content=message.value.trim();if(!name){nickname.focus();showToast("请先填写昵称");return}if(!content){message.focus();showToast("留言内容不能为空");return}const submit=form.querySelector(".submit-button");submit.disabled=true;try{const data=await api("/messages",{method:"POST",body:JSON.stringify({name,mood:mood.value,content,visitorId:visitorId()})});if(data.deleteToken)saveDeleteToken(data.message.id,data.deleteToken);if(remember.checked)storageSet(NAME_KEY,name);else try{localStorage.removeItem(NAME_KEY)}catch{}message.value="";charCount.textContent="0";search.value="";sort.value="newest";messages.unshift(data.message);render(true);showToast("留言发布成功")}catch(error){showToast(error.message)}finally{submit.disabled=false}});
message.addEventListener("input",()=>charCount.textContent=message.value.length);
list.addEventListener("click",async e=>{const btn=e.target.closest("button[data-action]"),card=e.target.closest(".message-card");if(!btn||!card)return;const item=messages.find(x=>String(x.id)===card.dataset.id);if(!item)return;btn.disabled=true;try{if(btn.dataset.action==="like"){const data=await api(`/messages/${encodeURIComponent(item.id)}/like`,{method:"POST",body:JSON.stringify({visitorId:visitorId()})});item.liked=data.liked;item.likes=data.likes;btn.classList.toggle("is-liked",item.liked);btn.setAttribute("aria-label",item.liked?"取消点赞":"点赞");const number=btn.querySelector("span");if(number)number.textContent=String(item.likes);likeCount.textContent=String(messages.reduce((n,x)=>n+x.likes,0))}else if(btn.dataset.action==="delete"){const token=deleteTokens()[item.id];await api(`/messages/${encodeURIComponent(item.id)}`,{method:"DELETE",headers:{"X-Delete-Token":token||"","X-Visitor-Id":visitorId()}});messages=messages.filter(x=>x.id!==item.id);render(false);showToast("留言已删除")}}catch(error){showToast(error.message)}finally{btn.disabled=false}});
search.addEventListener("input",()=>render(false));sort.addEventListener("change",()=>render(false));
function initTheme(){const root=document.documentElement;let saved=storageGet("card-theme");const theme=saved||(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark");apply(theme);themeToggle.addEventListener("click",()=>{const next=root.classList.contains("light")?"dark":"light";apply(next);storageSet("card-theme",next)});function apply(t){const light=t==="light";root.classList.toggle("light",light);themeToggle.setAttribute("aria-pressed",String(light));themeToggle.setAttribute("aria-label",light?"切换到深色主题":"切换到浅色主题")}}
nickname.value=storageGet(NAME_KEY);$("#currentYear").textContent=new Date().getFullYear();initTheme();loadMessages();
