"use strict";
const $=s=>document.querySelector(s),config=window.AUCEI_GUESTBOOK_CONFIG||{},API=String(config.apiBaseUrl||"").replace(/\/$/,"");
const loginView=$("#loginView"),dashboard=$("#dashboard"),loginForm=$("#loginForm"),keyInput=$("#adminKey"),loginButton=$("#loginButton"),list=$("#adminList"),empty=$("#adminEmpty"),pager=$("#adminPager"),search=$("#adminSearch"),filter=$("#statusFilter"),toast=$("#adminToast"),modal=$("#deleteConfirm"),themeToggle=$("#themeToggle");
let key=sessionStorage.getItem("aucei-admin-key")||"",page=1,totalPages=1,searchTimer=0,pendingDelete=null;
const expandedMessages=new Set();
const esc=v=>{const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML},statusText=s=>({approved:"已显示",hidden:"已隐藏"}[s]||s),time=v=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v));

function initTheme(){
  const root=document.documentElement,saved=localStorage.getItem("card-theme"),initial=saved||(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark");
  commitTheme(initial);
  themeToggle.addEventListener("click",()=>{
    const next=root.classList.contains("light")?"dark":"light";
    root.classList.add("theme-changing");
    commitTheme(next);
    localStorage.setItem("card-theme",next);
    window.setTimeout(()=>root.classList.remove("theme-changing"),480);
  });
  function commitTheme(theme){
    const light=theme==="light";
    root.classList.toggle("light",light);
    themeToggle.setAttribute("aria-pressed",String(light));
    themeToggle.setAttribute("aria-label",light?"切换到深色主题":"切换到浅色主题");
  }
}
function notify(t){toast.textContent=t;toast.classList.add("open");setTimeout(()=>toast.classList.remove("open"),1800)}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json","X-Admin-Key":key,...opt.headers}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`请求失败 (${r.status})`);return d}
function setLoggedIn(v){loginView.hidden=v;dashboard.hidden=!v}
async function login(){loginButton.disabled=true;loginButton.textContent="正在验证…";try{key=keyInput.value.trim();await api("/admin/login",{method:"POST"});sessionStorage.setItem("aucei-admin-key",key);setLoggedIn(true);await loadAll();notify("登录成功")}catch(e){key="";sessionStorage.removeItem("aucei-admin-key");notify(e.message)}finally{loginButton.disabled=false;loginButton.textContent="进入管理后台"}}
async function loadAll(){await Promise.all([loadStats(),loadMessages()]);$("#lastUpdate").textContent=`最后刷新：${new Date().toLocaleTimeString("zh-CN")}`}
async function loadStats(){const d=await api("/admin/stats"),cards=[[d.messages,"留言"],[d.replies,"回复"],[d.likes,"点赞"],[d.today,"今日新增"],[d.hidden,"已隐藏"]];$("#stats").innerHTML=cards.map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join("")}
function detailMarkup(x){const q=[["详细地址",x.detailedAddress||"未获取"],["设备",x.deviceType||"未获取"],["型号",x.deviceModel||"未提供"],["系统",x.osName||"未获取"],["访问环境",x.browserName||"未获取"],["浏览器内核",x.browserEngine||"未获取"]];return `<div class="admin-details">${q.map(([a,b])=>`<div class="admin-detail"><span>${a}</span><strong>${esc(b)}</strong></div>`).join("")}</div>`}
function replyMarkup(r){return `<article class="admin-reply" data-reply="${esc(r.id)}"><div class="reply-head"><div><strong>${esc(r.name)}</strong> <span class="status ${esc(r.status)}">${statusText(r.status)}</span></div><span class="meta">${time(r.createdAt)}${r.region?` · ${esc(r.region)}`:""}</span></div><p>${r.replyToName?`回复 @${esc(r.replyToName)}：`:""}${esc(r.content)}</p>${detailMarkup(r)}<div class="reply-tools">${r.status!=="approved"?'<button class="action approve" data-action="reply-status" data-status="approved">显示</button>':""}${r.status!=="hidden"?'<button class="action hide" data-action="reply-status" data-status="hidden">隐藏</button>':""}<button class="action delete" data-action="reply-delete">永久删除</button></div></article>`}
function cardMarkup(m){return `<article class="admin-card" data-id="${esc(m.id)}"><div class="card-main"><div class="card-head"><div class="author"><strong>${esc(m.name)} ${esc(m.mood)}</strong><div class="meta">${time(m.createdAt)}${m.region?` · ${esc(m.region)}`:""} · #${esc(String(m.id).slice(-6))}</div></div><span class="status ${esc(m.status)}">${statusText(m.status)}</span></div><p class="body">${esc(m.content)}</p>${detailMarkup(m)}<div class="card-foot"><div class="counts"><span class="count-item" aria-label="点赞 ${m.likes}"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"></path></svg><b>${m.likes}</b></span><span class="count-item" aria-label="回复 ${m.replyCount}"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M9 17H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-5l-5 4v-4Z"></path></svg><b>${m.replyCount}</b></span></div><div class="actions">${m.status!=="approved"?'<button class="action approve" data-action="message-status" data-status="approved">显示</button>':""}${m.status!=="hidden"?'<button class="action hide" data-action="message-status" data-status="hidden">隐藏</button>':""}<button class="action delete" data-action="message-delete">永久删除</button></div></div></div>${m.replies.length?`<button class="reply-toggle" data-action="toggle-replies">${expandedMessages.has(String(m.id))?"收起回复":`查看 ${m.replies.length} 条回复`}</button><div class="replies" ${expandedMessages.has(String(m.id))?"":"hidden"}><div class="reply-list">${m.replies.map(replyMarkup).join("")}</div></div>`:""}</article>`}
async function loadMessages(){list.setAttribute("aria-busy","true");try{const p=new URLSearchParams({page:String(page),pageSize:"5"});if(search.value.trim())p.set("q",search.value.trim());if(filter.value)p.set("status",filter.value);const d=await api(`/admin/messages?${p}`);totalPages=d.totalPages;list.innerHTML=d.items.map(cardMarkup).join("");empty.hidden=d.items.length>0;$("#resultSummary").textContent=`共 ${d.total} 条`;pager.hidden=d.totalPages<=1;$("#pageInfo").textContent=`第 ${d.page} / ${d.totalPages} 页`;$("#adminPrev").disabled=d.page<=1;$("#adminNext").disabled=d.page>=d.totalPages}catch(e){if(/密钥/.test(e.message)){logout();}notify(e.message)}finally{list.setAttribute("aria-busy","false")}}
async function setStatus(type,id,status){try{await api(`/admin/${type === "reply" ? "replies" : "messages"}/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status})});await loadAll();notify(status==="approved"?"已恢复显示":"已隐藏")}catch(e){notify(e.message)}}
function openDelete(type,id,name){pendingDelete={type,id};$("#deleteText").textContent=`将永久删除${type==="message"?`“${name}”的留言及其回复和点赞`:"这条回复"}，删除后无法恢复。`;modal.hidden=false}
function closeDelete(){modal.hidden=true;pendingDelete=null}
async function doDelete(){if(!pendingDelete)return;const b=$("#confirmDelete");b.disabled=true;b.textContent="正在删除…";try{await api(`/admin/${pendingDelete.type === "reply" ? "replies" : "messages"}/${encodeURIComponent(pendingDelete.id)}`,{method:"DELETE"});closeDelete();await loadAll();notify("已永久删除")}catch(e){notify(e.message)}finally{b.disabled=false;b.textContent="永久删除"}}
function logout(){key="";sessionStorage.removeItem("aucei-admin-key");setLoggedIn(false);keyInput.value=""}
loginForm.addEventListener("submit",e=>{e.preventDefault();login()});$("#logoutButton").addEventListener("click",logout);$("#refreshButton").addEventListener("click",loadAll);$("#adminPrev").addEventListener("click",()=>{if(page>1){page--;loadMessages()}});$("#adminNext").addEventListener("click",()=>{if(page<totalPages){page++;loadMessages()}});filter.addEventListener("change",()=>{page=1;loadMessages()});search.addEventListener("input",()=>{clearTimeout(searchTimer);page=1;searchTimer=setTimeout(loadMessages,250)});modal.addEventListener("click",e=>{if(e.target.hasAttribute("data-close"))closeDelete()});$("#confirmDelete").addEventListener("click",doDelete);
list.addEventListener("click",e=>{const b=e.target.closest("button[data-action]"),card=e.target.closest(".admin-card");if(!b||!card)return;const id=card.dataset.id,a=b.dataset.action;if(a==="toggle-replies"){const box=card.querySelector(".replies"),opening=box.hidden;box.hidden=!opening;if(opening)expandedMessages.add(String(id));else expandedMessages.delete(String(id));b.textContent=opening?"收起回复":`查看 ${box.querySelectorAll(".admin-reply").length} 条回复`;return}if(a==="message-status")return setStatus("message",id,b.dataset.status);if(a==="message-delete")return openDelete("message",id,card.querySelector(".author strong").textContent);const reply=b.closest(".admin-reply");if(!reply)return;if(a==="reply-status")return setStatus("reply",reply.dataset.reply,b.dataset.status);if(a==="reply-delete")return openDelete("reply",reply.dataset.reply,"")});
initTheme();
if(key){setLoggedIn(true);loadAll().catch(()=>logout())}else setLoggedIn(false);